### PR TITLE
Update readme transaltion (IEP-784)

### PR DESCRIPTION
**Pull request by NatashaLi-ESPRESSIF**
## Description

Update the Chinese translation of readme file

### Summary by CodeRabbit

- New Feature: Added a method to get available ESP targets based on the toolchains in `ESPToolChainManager.java`.
- Refactor: Replaced manual addition of launch targets with a call to `addToolchainBasedTargets` in `SerialFlashLaunchTargetProvider.java`.
- Refactor: Modified `getArch()` and `getIDFTargetList()` methods in `NewSerialFlashTargetWizardPage.java` for improved type safety and encapsulation.
- Documentation: Updated Espressif-IDE version and download links in `Espressif-IDE.md`.
- Documentation: Added instructions for configuring esp-idf Clangd LSP in `clangd_cdt_support.md`.
- Chore: Added filters to exclude certain resources from being processed by Eclipse in multiple `.project` files.
- Style: Changed `org.eclipse.jdt.core.compiler.problem.nullReference` preference from "error" to "warning" in several `.prefs` files.

### CODE REVIEW

**Comment by NatashaLi-ESPRESSIF** [comment]
@leeebo, pls review!

cc: @alirana01

**Comment by NatashaLi-ESPRESSIF** [comment]
@alirana01 , can you pls help with these two failed jobs?

**Comment by alirana01** [comment]
> @alirana01 , can you pls help with these two failed jobs?

@NatashaLi-ESPRESSIF I am looking into this

**Comment by kolipakakondal** [comment]
Hi @alirana01 Could you rebase on the latest master branch? I think the build should go through this time

**Comment by kolipakakondal** [comment]
Hi @alirana01 Could you please check this and close the PR?

**Comment by NatashaLi-ESPRESSIF** [comment]
@alirana01  can you pls close this PR since i have merged the updates into https://github.com/espressif/idf-eclipse-plugin/pull/813?

**Pull request closed without merging**
