### PR TITLE
feat: added support for multi_config

### PR DESCRIPTION
**Pull request by sigmaaa**
## Description

added ability to run sdkconfig from any build folder

Fixes # ([IEP-1250](https://jira.espressif.com:8443/browse/IEP-1250))

## Type of change

Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## How has this been tested?

- Create the multi_conf project example. 
- Try to build with different custom build folders
- run sdkconfigs from different directories 

**Test Configuration**:
* ESP-IDF Version:
* OS (Windows,Linux and macOS):

## Dependent components impacted by this PR:

- Component 1
- Component 2

## Checklist
- [x] PR Self Reviewed
- [x] Applied Code formatting
- [ ] Added Documentation
- [ ] Added Unit Test
- [x] Verified on all platforms - Windows,Linux and macOS

## Summary by CodeRabbit

- **New Features**
	- Improved handling of custom build directories in project settings.
	- Enhanced SDK configuration management with new methods for setting and managing build folders.

- **Bug Fixes**
	- Corrected logic for extracting build directories from CMake arguments.

- **Enhancements**
	- Refined error handling and UI creation for SDK configuration files.
	- Updated logic in configuration server management for better performance and reliability.

### CODE REVIEW

**Review by kolipakakondal — APPROVED** [review]
LGTM

**Comment by sigmaaa** [comment]
> @sigmaaa hi !
> 
> Tested under: OS - Windows 10 ESP-IDF: v5.2
> 
> able to build multi config to same project. ✔️ able to open every sdkconfig file ✔️ but if open sdk file from every "build" folder together - then sometime it lead to this error:
> 
> image

Hi @AndriiFilippov, @kolipakakondal, 

fixed in the last commit, PTAL

**Review by sigmaaa — COMMENTED** [review]
Self reviewed

**Review by kolipakakondal — APPROVED** [review]
LGTM

**Comment by AndriiFilippov** [comment]
@sigmaaa hi ! 

Tested under: 
OS - Windows 10, Linux, MacOS 

LGTM 👍 


There is some mistakes in docs, please update it. 

Example does not work with provided command `idf.py -B build_prod1 -D SDKCONFIG_DEFAULTS="sdkconfig.prod_common;sdkconfig.prod1" build` 
Should be: `idf.py -B build_prod1 -D SDKCONFIG_DEFAULTS= sdkconfig.prod_common;sdkconfig.prod1 build`

[sdkconfig.prod1sdkconfig.prod1](https://github.com/espressif/esp-idf/tree/master/examples/build_system/cmake/multi_config#production-build)

Same here and this typo as well: 
|
image

https://github.com/espressif/esp-idf/tree/master/examples/build_system/cmake/multi_config#production-build-output




Moreover, I was not able to set different sdkconfigs for particular "build" folder, 
it always reset "sdkconfig.prod" files to default. 🚫

**Comment by AndriiFilippov** [comment]
@sigmaaa hi ! 

Tested under: 
OS - Windows 10 / MacOS 

LGTM 👍

**Pull request merged**
