### PR TITLE
IEP-963 Test coverage ProcessBuilderFactory class

### PR DESCRIPTION
**Pull request by sigmaaa**
## Description

test coverage for ProcessBuilderFactory class

Fixes # ([IEP-963](https://jira.espressif.com:8443/browse/IEP-963))

## Type of change

Please delete options that are not relevant.
- New feature (non-breaking change which adds functionality)

## How has this been tested?
The source code has not changed, so just run unit tests

**Test Configuration**:
* ESP-IDF Version:
* OS (Windows,Linux and macOS):

## Dependent components impacted by this PR:
- unit tests

## Checklist
- [x] PR Self Reviewed
- [x] Applied Code formatting
- [ ] Added Documentation
- [x] Added Unit Test
- [x] Verified on all platforms - Windows,Linux and macOS

### CODE REVIEW

**Comment by sigmaaa** [comment]
since tests fail on windows, will use a different approach with` private final String[] cmd = {"cmd", "/c"};` commands for Windows and
`private final String[] bash = {"bash", "-c"}; `for Unix

**Comment by sigmaaa** [comment]
Rewrote tests to be compatible with Windows. Also, removed hard-coded arguments and non-reachable areas related to these arguments. @kolipakakondal, @alirana01 please, take a look at this commit [clean up hard coded arguments and removing dead code](https://github.com/espressif/idf-eclipse-plugin/pull/769/commits/a9b6ba83881b49853b05db137ff98236e7b11965)

**Review by alirana01 — COMMENTED** [review]
Its a well written test with good idea but don't you think we should try to run some actual process with the commands so we can verify some kind of output that may also open up some tests with env variables being tested properly?

**Comment by kolipakakondal** [comment]
Not now, we can optimize this code with ExecutorService for creating threads and joining them

**Review by kolipakakondal — APPROVED** [review]
LGTM

**Pull request merged**
