### PR TITLE
IEP-370: NVS partition editor

### PR DESCRIPTION
**Pull request by sigmaaa**
## Description

Check more about NVS partition editor utility from esp-idf, check this here https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/nvs_partition_gen.html

This PR includes the preparation for refactoring PartitionTableDataUtil class to be extended from AbstactTableDataService

Fixes # ([IEP-370](https://jira.espressif.com:8443/browse/IEP-370))

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How has this been tested?

Test 1:
- Right click on the project in the project explorer -> click ESP-IDF: NVS Table Editor -> The table with default values is provided
- Click Save and Quit -> nvs.csv should be created in project directory

Test 2:
- Try to put incorrect values into the field (More info [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/nvs_partition_gen.html)) and Save and then generate nvs.bin 
- In this case, you should see an error notification with a clear error message as to what is wrong.

Test 3:
- Input correct values -> Save -> Generate Partition
- In this case, you should see an informational message about the successful saving and creation of partitions.
- nvs.bin should be present in project directory

Test 4: 
- Generate partition with and without encryption
- Generate key and select the encryption key

**Test Configuration**:
* ESP-IDF Version:
* OS (Windows,Linux and macOS):

## Dependent components impacted by this PR:

- NVS Table Editor

## Checklist
- [x] PR Self Reviewed
- [x] Applied Code formatting
- [ ] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

### CODE REVIEW

**Comment by sigmaaa** [comment]
Need to add Espressif Copyright License Headers

**Comment by AndriiFilippov** [comment]
@sigmaaa hi!

Tested under:
OS: Windows 10
ESP-IDF: v5.0

Maximize editor window -> click any of "Add row" / "Delete row" / "Encrypt?"  -> editor window Restore down itself.

**Comment by AndriiFilippov** [comment]
@sigmaaa 

"Delete Selected" still works and ask permission to delete row if nothing selected.

image

**Comment by AndriiFilippov** [comment]
@sigmaaa 

Test 1:  👍 
Right click on the project in the project explorer -> click ESP-IDF: NVS Table Editor -> The table with default values is provided
Click Save and Quit -> nvs.csv should be created in project directory.

Test 2:  👍 
Try to put incorrect values into the field (More info [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/nvs_partition_gen.html)) and Save and then generate nvs.bin
In this case, you should see an error notification with a clear error message as to what is wrong.

Test 3:  👍 
Input correct values -> Save -> Generate Partition
In this case, you should see an informational message about the successful saving and creation of partitions.
nvs.bin should be present in project directory

Test 4:    👍 
Generate partition with and without encryption
Generate key and select the encryption key

**Comment by kolipakakondal** [comment]
Screenshot 2022-12-21 at 12 33 16 PM

Can we avoid showing dialog over dialog which violates best UI practices?

**Comment by kolipakakondal** [comment]
Screenshot 2022-12-21 at 12 40 47 PM

Add specific icon for `ESP-IDF: NVS Table Editor`

**Comment by kolipakakondal** [comment]
NPE when I selected to click on `Save and Quit` after all the entries are deleted from the editor
 
Screenshot 2022-12-21 at 12 47 31 PM

```
!STACK 0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at com.espressif.idf.ui.nvs.dialog.NvsEditorDialog.validateBeansBeforeSaving(NvsEditorDialog.java:512)
	at com.espressif.idf.ui.nvs.dialog.NvsEditorDialog$6.run(NvsEditorDialog.java:485)
	at com.espressif.idf.ui.nvs.dialog.NvsEditorDialog.okPressed(NvsEditorDialog.java:623)
	at org.eclipse.jface.dialogs.Dialog.buttonPressed(Dialog.java:468)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1522)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1545)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1530)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4310)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3883)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at com.espressif.idf.ui.nvs.handlers.NvsEditorHandler.execute(NvsEditorHandler.java:33)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1522)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1545)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1530)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4310)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3883)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1041)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**Comment by kolipakakondal** [comment]
Screenshot 2022-12-21 at 12 49 38 PM

To show this kind of errors, we could always use the Title Area dialog so that it offers the space to show the error at the top of the dialog so that we could avoid showing multiple dialogs on eclipse workbench

**Comment by kolipakakondal** [comment]
> First entry should be of type "namespace"

as this requirement is mandatory, we can keep it by default and will not allow the user to change the **Type** for the first row

**Comment by kolipakakondal** [comment]
Refresh project explorer after generating partition keys

**Review by kolipakakondal — CHANGES_REQUESTED** [review]
Thanks for the PR @sigmaaa Looks good. However, it would be great if we could address the mentioned changes to improve usability.

**Comment by sigmaaa** [comment]
> 1. Refresh project explorer after generating partition keys
> 2. Add logs for troubleshooting further. I don't see anything recorded in the log after clicking on generate or save
> 3. We could increase the default table editor size to visually look good - Maybe we could show 3 rows
> 4. Buttons don't appear like buttons - we could follow standard buttons with a border
> 5. Add a border to the table

Hi @kolipakakondal, I added the mentioned improvements to the latest commits. 
The only two things left:
- update the icon 
- Do not allow the user to edit the first row (except the key) of the table 

I have a question about the second option (`Do not allow the user to edit the first row (other than the key) of the table`). What is the best way to achieve this? My idea is to not show the first line and make the default key a separate text field, but perhaps there is a prettier way.

@AndriiFilippov Could you test it one more time as there are big changes in the UI? Thanks

**Comment by sigmaaa** [comment]
For further research: maybe we can improve data validation with data bindings.

**Comment by kolipakakondal** [comment]
Thanks @sigmaaa for the PR changes. 

> I have a question about the second option (`Do not allow the user to edit the first row (other than the key) of the table`). What is the best way to achieve this? My idea is to not show the first line and make the default key a separate text field, but perhaps there is a prettier way.

I think that should be fine, as long as we are making it clear to the user.

Maybe we frame something like this or better
> Provide a name for type "namespace", this would be the first entry in the NVS Partition table

**Comment by AndriiFilippov** [comment]
@sigmaaa hi ! 


Also please, take a look at this one 

Steps: open ESP-IDF NVS Table Editor -> Select "Encrypt?" -> Generate Partition -> error.  



image

**Comment by sigmaaa** [comment]
> @sigmaaa hi !
> 
> Also please, take a look at this one
> 
> Steps: open ESP-IDF NVS Table Editor -> Select "Encrypt?" -> Generate Partition -> error.
> 
> image

Hi @AndriiFilippov, thanks for noticing it. Fixed in the latest commit

**Comment by AndriiFilippov** [comment]
@sigmaaa hi ! 

- do not allow to edit and delete first row
- update icon
- replace .pack() with refresh() for add/delete

Tested. LGTM.

**Comment by AndriiFilippov** [comment]
@sigmaaa hi ! 


Tested:    _fix extensions filtering for windows_  👍 



image

**Review by AndriiFilippov — APPROVED** [review]

**Review by kolipakakondal — APPROVED** [review]

**Pull request merged**
