### PR TITLE
IEP-886 Launch Configuration does not save custom build folder path

### PR DESCRIPTION
**Pull request by sigmaaa**
## Description

Launch configuration was not able to restore the custom build folder after closing and reopening the project. As figured out the Instance Scope preference are cleaned up after the closing of the project, so as a solution I decided to move to store preferences in the launch configuration. It also makes code cleaner and allows us to export the launch configuration with all preferences which are set up there.

Also, as part of PR was some related refactoring of the IDFBuildConfiguration class. The goal of the refactoring was to reduce the complexity of the code. After the refactoring, the build command always picks up the last selected build folder (Previously, it required the restart of the eclipse or editing the cmake file)

Was found and fixed the typo: we were using buildCommand instead of cleanCommand for the cleanCommandTxt.

One last thing, during testing, I found and fixed the root of the issue with the launch configuration, due to which, sometimes the launch configuration could not pick up the selected project and the selected project was always the default after reopening the launch configuration.

Fixes # ([IEP-886](https://jira.espressif.com:8443/browse/IEP-886))

## Type of change

Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)

## How has this been tested?

Test 1:
- add a custom build folder, close-reopen the project -> make sure that the custom build folder hasn't changed 
Test 2:
- make sure that the refactoring didn't break the current functionality related to the build, indexer, and other related components. We need to do as many tests as possible by comparing behavior on the master and on this branch 

**Test Configuration**:
* ESP-IDF Version:
* OS (Windows,Linux and macOS):

## Dependent components impacted by this PR:

- Build command
- Launch configuration (Build Tab, Main tab)
- custom build folder

## Checklist
- [ ] PR Self Reviewed
- [ ] Applied Code formatting
- [ ] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

### CODE REVIEW

**Comment by AndriiFilippov** [comment]
Hi @sigmaaa ! 

Tested under: 
OS - Windows 10
ESP-IDF: v5.0 

Launch Configuration -> New Launch Configuration -> click "Next" -> click "Back" -> the "Finish" button become active.
If you ignore and create new configuration -> the name of ORIGINAL configuration get duplicate number every time you click on  "gear" icon in Launch Configuration Menu: 

image

**Comment by AndriiFilippov** [comment]
@sigma hi ! 

Also once I "Close Project" -> "Open Project" -> and then create new Launch Configuration without waiting for Indexer finish -> program stuck .

**Comment by AndriiFilippov** [comment]
@sigmaaa hi ! 
 
Tested under: 
OS - Windows 10 

Create new custom build folder config -> build project -> right click on project in Project Explorer  and do "Close Project" -> then close IDE -> reopen IDE -> right click on project in Project Explorer  and do "Open Project" -> try to create NEW Launch Configuration -> ERROR



ERROR LOG:

```
Problems occurred when invoking code from plug-in: "org.eclipse.jface".
java.lang.NullPointerException: Cannot invoke "org.eclipse.cdt.core.settings.model.ICConfigurationDescription.getId()" because the return value of "org.eclipse.cdt.core.settings.model.ICProjectDescription.getActiveConfiguration()" is null
	at com.espressif.idf.launch.serial.ui.internal.CMakeMainTab2.initializeCProject(CMakeMainTab2.java:257)
	at com.espressif.idf.launch.serial.ui.internal.CMakeMainTab2.setDefaults(CMakeMainTab2.java:220)
	at org.eclipse.debug.ui.AbstractLaunchConfigurationTabGroup.setDefaults(AbstractLaunchConfigurationTabGroup.java:80)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupWrapper.setDefaults(LaunchConfigurationTabGroupWrapper.java:220)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog.doSetDefaults(LaunchConfigurationsDialog.java:1162)
	at org.eclipse.launchbar.ui.internal.dialogs.NewLaunchConfigEditPage$LaunchConfigurationDialogExt.doSetDefaults(NewLaunchConfigEditPage.java:187)
	at org.eclipse.launchbar.ui.internal.dialogs.NewLaunchConfigEditPage.handlePageChanging(NewLaunchConfigEditPage.java:99)
	at org.eclipse.jface.wizard.WizardDialog$6.run(WizardDialog.java:1566)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.wizard.WizardDialog.firePageChanging(WizardDialog.java:1563)
	at org.eclipse.jface.wizard.WizardDialog.doPageChanging(WizardDialog.java:931)
	at org.eclipse.jface.wizard.WizardDialog.showPage(WizardDialog.java:1215)
	at org.eclipse.jface.wizard.WizardDialog.nextPressed(WizardDialog.java:918)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:469)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.launchbar.ui.controls.internal.ConfigSelector$3.mouseUp(ConfigSelector.java:182)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:224)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```
image

**Comment by AndriiFilippov** [comment]
> > Hi @sigmaaa !
> > Tested under: OS - Windows 10 ESP-IDF: v5.0
> > Launch Configuration -> New Launch Configuration -> click "Next" -> click "Back" -> the "Finish" button become active. If you ignore and create new configuration -> the name of ORIGINAL configuration get duplicate number every time you click on "gear" icon in Launch Configuration Menu:
> > image
> 
> Hi @AndriiFilippov should be fixed after the latest commit

Hi @sigmaaa ! 

Tested under: 
OS - Windows 10 

The "Finish" button is still active but the "ORIGINAL configuration get duplicate number" issue has gone.

**Comment by AndriiFilippov** [comment]
@sigmaaa hi ! 

Tested under: 
OS - Windows 10 

create custom build folder -> build project  -> create new launch config without custom build folder ->  build - > error 



image

**Review by kolipakakondal — APPROVED** [review]
LGTM

**Comment by AndriiFilippov** [comment]
Hi @sigmaaa ! 

Tested under: 

OS- Windows10 / Linux Ubuntu 

LGTM

**Pull request merged**
