### PR TITLE
IEP-825: Fixing issues with tools installation wizard on MAC OS

### PR DESCRIPTION
**Pull request by alirana01**
## Description

There were some issues in tools installation wizard particularly on Mac os due to some java functions not working because of limited permissions there while extraction of the files from a gz archive

Fixes # ([IEP-825](https://jira.espressif.com:8443/browse/IEP-825))

## Type of change

Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)

## How has this been tested?

This change requires that tools installation wizard to be tested on Mac os and after that we need to verify this on other platforms as well. If any issues found for those they will be taken in their respective tickets 

**Test Configuration**:
* ESP-IDF Version: **All**
* OS (Windows,Linux and macOS): **All**

## Checklist
- [x] PR Self Reviewed
- [x] Applied Code formatting
- [ ] Verified on all platforms - Windows,Linux and macOS

### CODE REVIEW

**Review by alirana01 — COMMENTED** [review]
Code refactoring to be done separately for reusing and boxing code in one area

**Review by sigmaaa — APPROVED** [review]
LGTM. Test case: Clean the workspace, Tried to install all recommended tools on mac, create a new project and build it. Works fine

**Comment by kolipakakondal** [comment]
Hi @AndriiFilippov Please verify

**Comment by AndriiFilippov** [comment]
Hi @alirana01 ! 

Tested under:
OS - Windows 10 / Linux Ubuntu / MacOS 
ESP-IDF: v5.0 / master

Was able to install tools using tools wizard /openOCD installed/ check the OpenOCD preferences 👍  / build project 
LGTM.

**Review by AndriiFilippov — APPROVED** [review]

**Comment by alirana01** [comment]
> Hi @alirana01 !
> 
> Tested under: OS - Windows 10 / Linux Ubuntu / MacOS ESP-IDF: v5.0 / master
> 
> Was able to install tools using tools wizard /openOCD installed/ check the OpenOCD preferences 👍 / build project LGTM.

Thank you @AndriiFilippov can you also please make sure to install only selected tools not all and see if the tools are installed and try installing recommended versions there as well.

**Comment by AndriiFilippov** [comment]
@alirana01 hi ! 
Tested 

> Thank you @AndriiFilippov can you also please make sure to install only selected tools not all and see if the tools are installed and try installing recommended versions there as well.

@alirana01 hi ! 
Tested: 
OS - Windows 10 / Linux Ubuntu.      (have issue with my  MacOS) 

Windows - LGTM 
Linux:  tested and create new ticket 
https://jira.espressif.com:8443/browse/IEP-888

**Comment by alirana01** [comment]
I am merging and closing this as the issues are handled in the different epic now the main issue for this PR related to MacOS and extraction of tar.gz is resolved in this one the bugs are now tackled in the tools epic

**Pull request merged**
