### PR TITLE
IEP-990 Integration of esp-idf BoM

### PR DESCRIPTION
**Pull request by sigmaaa**
## Description

Added command, that represents [esp-idf-sbom command ](https://github.com/espressif/esp-idf-sbom). To run the command right click on the project -> ESP-IDF: SBOM Tool

Fixes # ([IEP-990](https://jira.espressif.com:8443/browse/IEP-990))

## Type of change

Please delete options that are not relevant.
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How has this been tested?

Test 1:
- Choose esp-idf master version -> Right click on the project -> ESP-IDF: SBOM Tool -> provide project_description.json from the project -> click OK -> `Running esp-idf-sbom command...` command is activated -> output is printed to the console
Test 2:
- repeat test 1, but choose option to redirect output to the file -> the result should be redirected in the file -> in the console output there will be the message with the hyperlink to the file -> by activating this link the file will be open with default editor

**Test Configuration**:
* ESP-IDF Version:
* OS (Windows,Linux and macOS):

## Dependent components impacted by this PR:

- ESP-IDF: SBOM Tool command

## Checklist
- [ ] PR Self Reviewed
- [ ] Applied Code formatting
- [ ] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

### Summary by CodeRabbit

- New Feature: Introduced a new tool called "SBOM Tool" to the ESP-IDF suite. 
- Usability: Added a user-friendly dialog box for running the `esp_idf_sbom` command. Users can now select a project description file, specify an output file path, and execute the command all within the dialog box. 
- Value Proposition: The tool enhances project management by generating a software bill of materials (SBOM) for ESP-IDF projects. 
- Usability: The dialog box also provides hyperlinks to open the output file in an editor, making it easier for users to access and review the command output.
- Usability: The tool will be installed automatically if not already present, simplifying the setup process for users.

### CODE REVIEW

**Comment by AndriiFilippov** [comment]
@sigmaaa hi ! 

Tested: 
OS - Windows 10 
ESP-IDF: master 

Create project - command "ESP-IDF: SBOM Tool" doesn't work 

ERROR LOG: 


```
org.eclipse.core.commands.ExecutionException: Error executing 'com.espressif.idf.ui.sbom': java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/AndriiFilippov/workspace9379992/qw2\build\project_description.json
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:170)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:645)
```

**Comment by AndriiFilippov** [comment]
@sigmaaa hi ! 

Tested under:
OS - Windows 10 
ESP-IDF: master


can't install BoM tool, incorrect Output File Path - getting error: 
image


```
E: cannot write to "/C:/Users/AndriiFilippov/workspace32323132313/qwe2ew\sbom.txt": [WinError 123] The filename, directory name, or volume label syntax is incorrect: '/C:'
Traceback (most recent call last):
  File "C:\Users\AndriiFilippov\.espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\esp_idf_sbom\libsbom\spdx.py", line 403, in write
    os.makedirs(dirpath, exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  [Previous line repeated 1 more time]
  File "<frozen os>", line 225, in makedirs
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '/C:'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AndriiFilippov\.espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\esp_idf_sbom\libsbom\spdx.py", line 419, in write
    log.err.die('cannot write to "{}": {}'.format(fn or 'stdout', e))
  File "C:\Users\AndriiFilippov\.espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\esp_idf_sbom\libsbom\log.py", line 94, in die
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\AndriiFilippov\.espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\esp_idf_sbom\__main__.py", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\AndriiFilippov\.espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\esp_idf_sbom\sbom.py", line 486, in main
    return args.func(args)
           ^^^^^^^^^^^^^^^
  File "C:\Users\AndriiFilippov\.espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\esp_idf_sbom\sbom.py", line 22, in cmd_create
    spdx_sbom.write(args.output_file)
  File "C:\Users\AndriiFilippov\.espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\esp_idf_sbom\libsbom\spdx.py", line 422, in write
    fd.close()
    ^^
UnboundLocalError: cannot access local variable 'fd' where it is not associated with a value
```

**Comment by AndriiFilippov** [comment]
@sigmaaa hi ! 

Tested under:
OS - Windows 10 
ESP-IDF: master

Steps:
Create - Build project - ESP-IDF: SBOM Tool - mark "Redirect output to the file" - put incorrect **Output File Path** / **Project Description** PATH  -  OK  button still active and let you in. 

image




Also, there is no input symbols validation.

**Comment by AndriiFilippov** [comment]
@sigmaaa hi ! 

Tested under: 

OS - Windows 10 
ESP-IDF: master 


Not able to create Output File: 

Steps:
Create - Build project - ESP-IDF: SBOM Tool - mark "Redirect output to the file" - click OK - error: 











image











image

**Comment by sigmaaa** [comment]
Hi @AndriiFilippov, thanks for reviewing. Mentioned errors should be fixed after latest commit

**Review by sigmaaa — COMMENTED** [review]
Self reviewed. Some code can be extracted to increase readability, for example, the part with PatternMatchListener. However, I'm not sure if it's necessary because most probably we will not have additional benefits from such abstraction.

**Comment by AndriiFilippov** [comment]
@sigmaaa hi ! 

OS - Windows 10 
ESP-IDF: master 

1) Empty PATH - OK button active. 

image



2) Able to create Output File but the file is not visible in Project Explorer: 

image

**Comment by AndriiFilippov** [comment]
@sigmaaa hi ! 

Tested: 
Linux Ubuntu 20.04 
ESP-IDF:  master

Empty PATH validation on Linux: 

Screenshot from 2023-10-17 15-38-50

**Comment by AndriiFilippov** [comment]
Screenshot from 2023-10-17 15-48-01

**Comment by AndriiFilippov** [comment]
@sigmaaa can't see project refreshing after sbom.txt created on Linux Ubuntu 20.04

**Comment by AndriiFilippov** [comment]
@sigmaaa hi ! 

Tested: 
OS: Windows 10 / Linux Ubuntu / MacOS

LGTM 👍

**Comment by sigmaaa** [comment]
added new icon

**Pull request merged**
