### PR TITLE
feat: improving UX during run/debug

### PR DESCRIPTION
**Pull request by sigmaaa**
## Description

This is an alternative to https://github.com/espressif/idf-eclipse-plugin/pull/806, since the approach with filtering run/debug configurations causes bugs and additional maintenance debt 

Fixes # ([IEP-957](https://jira.espressif.com:8443/browse/IEP-957))

## Type of change

Please delete options that are not relevant.
- New feature (non-breaking change which adds functionality)

## How has this been tested?

Test 1:
- Select a debug configuration with Run mode and click "Run" -> Popup appears with suitable launch config -> click launch -> verify functionality
Test 2 
- repeat test 1 for launch configuration with Debug mode
Test 3
- delete Debug config -> try to debug launch config -> message that suggesting create a debug config
Test 4
- Remove project from debug configuration -> try to launch/debug -> Edit config question provided 

**Test Configuration**:
* ESP-IDF Version:
* OS (Windows,Linux and macOS):

## Dependent components impacted by this PR:

- Launch/Debug configuration
- Run/Debug

## Checklist
- [x] PR Self Reviewed
- [x] Applied Code formatting
- [ ] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

## Summary by CodeRabbit

- **New Features**
    - Enhanced user interaction with new dialogs for selecting debug and launch configurations.
    - Improved UI with additional messages and labels for better clarity during configuration selection.

- **Enhancements**
    - Improved responsiveness in handling active launch target changes.
    - Enhanced execution event handling for launch configurations, offering improved user guidance.

- **Documentation**
    - Updated UI messages and documentation to align with new features and enhancements.

### CODE REVIEW

**Comment by AndriiFilippov** [comment]
@sigmaaa hi !

Tested under:

OS - Windows 10 
ESP-IDF: v5.1.2 

- Select a debug configuration with Run mode and click "Run" -> Popup appears with suitable launch config -> click launch -> verify functionality 🟢 
- Repeat test 1 for launch configuration with Debug mode 🟢 
- Delete Debug config -> try to debug launch config -> message that suggesting create a debug config 🟢 
- Remove project from debug configuration -> try to launch/debug -> Edit config question provided 🟢 
- Repeated tests with Multiple Launch Configs / Debug Configs 🟢 


🔴 Please, update text with Upper Case for those words and delete extra words. 

image


🔴 found a bug related to Launch Config name validation.

Create project A -> create Debug config "A config" -> Edit Debug Config -> Rename to "A" -> there is the warning message only BUT it is still possible to create one. 
image


If ignore it - in this particular PR it leads to the bug with empty list: 
image

**Comment by sigmaaa** [comment]
> @sigmaaa hi !
> 
> Tested under:
> 
> OS - Windows 10 ESP-IDF: v5.1.2
> 
> * Select a debug configuration with Run mode and click "Run" -> Popup appears with suitable launch config -> click launch -> verify functionality 🟢
> * Repeat test 1 for launch configuration with Debug mode 🟢
> * Delete Debug config -> try to debug launch config -> message that suggesting create a debug config 🟢
> * Remove project from debug configuration -> try to launch/debug -> Edit config question provided 🟢
> * Repeated tests with Multiple Launch Configs / Debug Configs 🟢
> 
> 🔴 Please, update text with Upper Case for those words and delete extra words.
> 
> image
> 
> 🔴 found a bug related to Launch Config name validation.
> 
> Create project A -> create Debug config "A config" -> Edit Debug Config -> Rename to "A" -> there is the warning message only BUT it is still possible to create one. image
> 
> If ignore it - in this particular PR it leads to the bug with empty list: image


Hi @AndriiFilippov, fixed messages in the latest commit. The empty list bug happens due to editing the configuration name to an existing one, which should not be allowed. It's a bug from Eclipse CDT, I guess and it will be easier to fix on the CDT side

**Comment by AndriiFilippov** [comment]
@sigmaaa hi ! 

OK, in this case everything LGTM 👍

**Review by AndriiFilippov — APPROVED** [review]

**Review by kolipakakondal — APPROVED** [review]
LGTM

**Pull request merged**
