### PR TITLE
IEP-975: Bug fix for recommended button in Tools Installation Wizard

### PR DESCRIPTION
**Pull request by alirana01**
## Description

Bug fix for recommended button in Tools Installation Wizard

Fixes # ([IEP-975](https://jira.espressif.com:8443/browse/IEP-975))

## Type of change

Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)

## How has this been tested?

Please use the reported flow to verify

image

**Test Configuration**:
* ESP-IDF Version: Any
* OS (Windows,Linux and macOS): Any

## Checklist
- [ ] PR Self Reviewed
- [ ] Applied Code formatting
- [ ] Verified on all platforms - Windows,Linux and macOS

### CODE REVIEW

**Review by kolipakakondal — APPROVED** [review]
LGTM. @AndriiFilippov Can you please check

**Review by sigmaaa — APPROVED** [review]
LGTM. Since we have some issues with the Python combo in the install tools command because users can't select the Python version they want to install the tools I suggested changing this combo from the read_only in this wizard as well. Let me know if you find it useful

**Comment by alirana01** [comment]
@AndriiFilippov please clarify and write steps I am confused on your reply

**Comment by alirana01** [comment]
@AndriiFilippov please try after the latest builds.

**Comment by AndriiFilippov** [comment]
@alirana01 hi ! 

Tested on: 
OS - Windows / Linux / MacOS 
ESP-IDF: v5.0 

Windows 👍 
Linux 👍 
On MacOS issue still persist. 
image

**Comment by AndriiFilippov** [comment]
Hi @alirana01  @kolipakakondal ! 

Tested under: 
OS - MacOS 

Still can't build project after installation via "Select Recommended" 
image


Check Product Information to see if the CMake is installed: 

image

**Comment by alirana01** [comment]
The issue mentioned with CMake is not part of this ticket it will be handled in the following one as its mac specific and could be resolved with configurations.
https://jira.espressif.com:8443/browse/IEP-987

**Pull request merged**
