### PR TITLE
IEP-1103: Fix for opening multiple files in sdkconfig editor and association of all the file starting with sdkconfig to the editor

### PR DESCRIPTION
**Pull request by alirana01**
## Description
By default the sdkconfig editor was only opening the sdkconfing file and even when manually opening other files with editor it was only showing contents of the default sdkconfig.

I have added required changes to configuration server to launch and handle different files at the same time on same project.

Fixes # ([IEP-1103](https://jira.espressif.com:8443/browse/IEP-1103))

## Type of change

Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Can be a breaking change 

## How has this been tested?

| Test 🧪                                                                                                                |
| -------------------------------------------------------------------------------------------------------------------- |
| Open the `sdkconfig` in editor, change some settings, and build the project.                                        |
| Open a different file, for example `sdkconfig.old`, make changes, and verify that changes do not affect other files. |
| Try opening and editing two files simultaneously in the editor.                                                      |
| Verify that any file starting with the name `sdkconfig` is opened in the `sdkconfig` editor when double-clicked.    |
| Ensure that the tab in the editor is showing the file name to avoid confusion when editing different files.         |

**Test Configuration**:
* ESP-IDF Version: any
* OS (Windows,Linux and macOS): all

## Checklist
- [x] PR Self Reviewed
- [x] Applied Code formatting
- [ ] Verified on all platforms - Windows,Linux and macOS

## Summary by CodeRabbit

- **New Features**
  - Enhanced configuration management with file-specific handling in configuration servers.
  - Implemented a method to check server process liveness.

- **Bug Fixes**
  - Improved process status checking with direct method calls.

- **Refactor**
  - Updated classes to support file-based operations for configuration handling.
  - Introduced a new key type for improved project and file mapping.

- **Documentation**
  - Added comments to clarify script constants.

- **Style**
  - Adjusted import statements to align with new functionality.

### CODE REVIEW

**Review by alirana01 — COMMENTED** [review]
Self Review

**Review by kolipakakondal — APPROVED** [review]
LGTM

**Comment by kolipakakondal** [comment]
@AndriiFilippov Can you verify this

**Comment by AndriiFilippov** [comment]
@alirana01 hi ! 

Steps:
Create project - build project - change some settings in sdkconfg file - build project - delete sdk file - change some settings in sdk old file - build project - sdk.old.old created instead of sdkconfig 

image


Once Build folder is deleted - build project - sdkconfig file created as it should be.

**Review by sigmaaa — COMMENTED** [review]
LGTM

**Comment by AndriiFilippov** [comment]
@alirana01 hi!

Steps: 

Create project - build - open sdk and change some settings - build again - open sdk file - close sdk file - open sdk.old file - close sdk.old file - build project - it re-build entire project again.

**Comment by kolipakakondal** [comment]
> - close sdk.old file - build project - it re-build entire project again.

Does it mean that sdk.old overwritting some of the settings in the original sdk file as well?

**Pull request merged**
