### PR TITLE
IEP-1074: Python dropdown removed

### PR DESCRIPTION
**Pull request by alirana01**
## Description
Python dropdown was causing some confusions to the users so it is now removed on Windows and a simple text box that points to the executable path of the python is kept

Fixes # ([IEP-1074](https://jira.espressif.com:8443/browse/IEP-1074))

## Type of change

Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)

## How has this been tested?

Tested on windows with install tools.

**Test Configuration**:
* ESP-IDF Version: any
* OS (Windows,Linux and macOS): Test on windows and also verify on Linux and Mac for normal workiing

## Checklist
- [x] PR Self Reviewed
- [x] Applied Code formatting
- [ ] Verified on all platforms - Windows,Linux and macOS

## Summary by CodeRabbit

- **New Features**
  - Introduced a new field for specifying the Python executable location in the Directory Selection Dialog.
  - Implemented validation for the Python executable path.

- **Refactor**
  - Removed outdated Python version selection functionality.

- **Documentation**
  - Added user-facing messages for invalid Python path validation.

### CODE REVIEW

**Review by alirana01 — COMMENTED** [review]
Self Review

**Review by kolipakakondal — APPROVED** [review]
Code LGTM

**Comment by kolipakakondal** [comment]
Hi @AndriiFilippov Please verify

**Review by sigmaaa — APPROVED** [review]
LGTM

**Comment by AndriiFilippov** [comment]
@alirana01 hi !

Should be some validation here?

image

**Comment by alirana01** [comment]
> @alirana01 hi !
> 
> Should be some validation here?
> 
> image

Yes will add this

**Comment by AndriiFilippov** [comment]
@alirana01 hi ! 

Tested under: 
OS - Windows 10 
ESP-IDF: v5.1.2 
Python: 3.7 / 3.8 / 3.11 

able to install tools with different Python versions, build + flash + monitor 👍 
LGTM 👍

**Pull request merged**
