### PR TITLE
IEP-1253: Welcome page ESP-IDF Manager link added

### PR DESCRIPTION
**Pull request by alirana01**
## Description

Welcome page ESP-IDF Manager link added

Fixes # ([IEP-1253](https://jira.espressif.com:8443/browse/IEP-1253))

## How has this been tested?

Verify the link to esp-idf manager works on the welcome page

**Test Configuration**:
* ESP-IDF Version: any
* OS (Windows,Linux and macOS): all

## Checklist
- [x] PR Self Reviewed
- [x] Applied Code formatting
- [x] Verified on all platforms - Windows,Linux and macOS

## Summary by CodeRabbit

- **New Features**
	- Introduced a modernized design for the web interface, enhancing aesthetics and usability.
	- Added a fixed sidebar for improved navigation, keeping essential sections visible while scrolling.
	- Enhanced accessibility with improved HTML structure and added alt attributes for images.

- **Bug Fixes**
	- Resolved layout issues by restructuring elements for better visual hierarchy and text legibility.

- **Style**
	- Updated button styles with hover effects to improve interactivity.
	- Refined various heading and paragraph styles for better readability.

### CODE REVIEW

**Review by kolipakakondal — CHANGES_REQUESTED** [review]
LGTM. Including this text would make things much clearer: 

`To get started, please click on the ESP-IDF Manager below to configure ESP-IDF and its tools.`

**Comment by AndriiFilippov** [comment]
@alirana01 hi ! 

Tested under: 
OS - Windows 11 

create workspace - close "Welcome" page -> go to "Help"-"Welcome" : 

image

**Comment by kolipakakondal** [comment]
> @alirana01 hi !
> 
> Tested under: OS - Windows 11
> 
> create workspace - close "Welcome" page -> go to "Help"-"Welcome" -> click "ESP-IDF Manager":
> 
> image

Hi @alirana01 Can you verify this problem and create a jira ticket if you're able to reproduce this? I was trying this on macOS and it seems to be working fine.

**Review by kolipakakondal — APPROVED** [review]
LGTM

**Pull request merged**
