### PR TITLE
IEP-801: Class cast exception during exporting debug config

### PR DESCRIPTION
**Pull request by sigmaaa**
## Description
fixes class cast exception during exporting debug configuration:
java.lang.ClassCastException: class org.eclipse.debug.internal.core.LaunchConfiguration cannot be cast to class org.eclipse.debug.core.ILaunchConfigurationWorkingCopy
Fixes # ([IEP-801](https://jira.espressif.com:8443/browse/IEP-801))

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How has this been tested?
- Right-click on project -> Run as.. -> Run Configurations.. -> Select debug configuration -> Right click on it -> try to export -> export successful

**Test Configuration**:
* ESP-IDF Version:
* OS (Windows,Linux and macOS):

## Dependent components impacted by this PR:

- SVD Path section in the debug configuration

## Checklist
- [ ] PR Self Reviewed
- [ ] Applied Code formatting
- [ ] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

### CODE REVIEW

**Comment by sigmaaa** [comment]
Looks like a few 5 commits came from another branch, let me clean it up a bit

**Comment by AndriiFilippov** [comment]
@sigmaaa hi ! 

Tested under: 
OS - Windows 10
ESP-IDF: v4.4

Case:  Right-click on project -> Run as.. -> Run Configurations.. -> Select debug configuration -> Right click on it -> export.
The "export" window is inactive.  Not able to click any button.

**Comment by sigmaaa** [comment]
Hi @AndriiFilippov,

Looks like it's a bug on the Eclipse side, which appears in a new version of Eclipse (4.25). I made some testing on 4.24 and 4.25 and can confirm that this issue happens only on 4.25, but it's still possible on to export the configuration on 4.25, but you have to close the background window first.

**Review by kolipakakondal — APPROVED** [review]
LGTM

**Pull request closed without merging**
