### PR TITLE
Added search tree filter to templates (IEP-300)

### PR DESCRIPTION
**Pull request by sigmaaa**
added search filter based on PatternFilter, which is searching elements in the tree structure

IEP-294

### CODE REVIEW

**Review by kolipakakondal — CHANGES_REQUESTED** [review]
1. Could you also enable the filter control when only the 'create a project using one of the templates` check box is checked? Otherwise, it will lead to confusion - users will type something and feel that it's not filtering correctly!
2. When you clear the filter text, the viewer should show the complete tree again
3.  It seems to be viewer is not refreshing after entering the filter text - I have to click one of the element to see the filtered content. 

I'm on macOS 10.15.7

**Comment by sigmaaa** [comment]
Now filter's text field is enabled only when the checkbox is selected. When the user moves the cursor over a disabled item, a tooltip appears: 
IEP-294 disabled field

**Comment by kolipakakondal** [comment]
> * When you clear the filter text, the viewer should show the complete tree again
> * It seems to be viewer is not refreshing after entering the filter text - I have to click one of the element to see the filtered content.

@sigmaaa Did you have a chance to verify the above scenarios?

**Comment by sigmaaa** [comment]
> > * When you clear the filter text, the viewer should show the complete tree again
> > * It seems to be viewer is not refreshing after entering the filter text - I have to click one of the element to see the filtered content.
> 
> @sigmaaa Did you have a chance to verify the above scenarios?

I tried on MacOS v. 10.15.7 and it looks the same as on windows for me. The next gif is showing functionality. I'm not clicking on field to refresh it, it's refresh automatically and after I'm clearing the filter text, the viewer is showing complete tree.
IEP-298-demonstration

**Pull request merged**
