### PR TITLE
IEP-238: IDF Monitor integration with Eclipse  (IEP-239)

### PR DESCRIPTION
**Pull request by kolipakakondal**
**ESP-IDF Serial Monitor Configuration dialog**

**ESP-IDF Serial Monitor Output**

**ESP-IDF Serial Monitor With Filter Options**

**ESP-IDF Serial Monitor With Filter Options Output**

**ESP-IDF Serial Monitor enabled with GDB stub invoked**

### CODE REVIEW

**Comment by sigmaaa** [comment]
Checked on window 10. LGTM

**Review by sigmaaa — APPROVED** [review]
I tested the serial monitor on windows 10, the terminal output looks the same. Tried on hello_world and blink projects with and without spi_flash:i filter option. Also checked with debug mode. LGTM

**Comment by kolipakakondal** [comment]
Hi @igrr - Can we merge this and release 1.3.0?

**Comment by igrr** [comment]
@kolipakakondal Yes, i think it is a great improvement over the previous terminal, would be good to release it.

**Comment by kolipakakondal** [comment]
Thanks @igrr for review

**Pull request merged**
