### PR TITLE
IEP-648: moving esp_idf_components to build folder

### PR DESCRIPTION
**Pull request by kolipakakondal**
## Description

To enable function definition navigation in the Eclipse IDE, as part of v2.5.0 we have added `esp_idf_components` to the root of the project. Based on the user's feedback we are moving this to the `/build/ide/esp_idf_components` to maintain sanity at the project level

Fixes # ([IEP-648](https://jira.espressif.com:8443/browse/IEP-648))
Screenshot 2022-07-26 at 1 50 47 PM

## Type of change

- New feature (non-breaking change which adds functionality)

## How has this been tested?

Case 1:
- Launch Espressif-IDE
- Build a Hello-world project 
- After the build, `esp_idf_components` folder should be created in the `/project/build/ide/ folder`
-  And, there shouldn't be any errors in the project source files and the user should be able to navigate the source code definition.

**Test Configuration**:
* ESP-IDF Version:master
* OS (Windows,Linux and macOS): All

## Dependent components impacted by this PR:

- Build
- Indexing
- Source Code Navigation
- Project Explorer folder structure

## Checklist
- [x] PR Self Reviewed
- [x] Applied Code formatting
- [ ] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

### CODE REVIEW

**Comment by AndriiFilippov** [comment]
@kolipakakondal hi ! 

Tested under: 
OS - Windows/Linux 

After the build, esp_idf_components folder is created in the /project/build/ide/ folder 👍 
But on both OS there is warnings like this(examples/get-started/hello-world/main/hello_world_main.c):  

**Linux:**
image


**Windows:**
image

Is it my environment issue or not ?

**Comment by kolipakakondal** [comment]
Thanks, @AndriiFilippov for verifying this. Looks like the issues mentioned are specific to windows and Linux environments I couldn't reproduce them in macOS.

I will set up a windows machine and work on these issues.

**Review by alirana01 — APPROVED** [review]
Code review LGTM

**Review by sigmaaa — APPROVED** [review]
LGTM

**Comment by kolipakakondal** [comment]
Hi @AndriiFilippov I have fixed indexer issues. Could you please check again? thank you
GIF 11-08-2022 5-37-05 pm

**Comment by gruenfron** [comment]
@kolipakakondal

hi, testing 563d1c3 did not fix the indexer problem under Linux for me:

before

however, after changing the project's indexer setting with enabled "Index source files not included in the build":

indexer

it seems to work fine:

after

Btw the component folder is perfectly located at 'build/ide/esp_idf_components'.

Hope this helps.

**Comment by AndriiFilippov** [comment]
Hi @kolipakakondal 

Tested under: 
OS - Windows 10 
ESP - IDF: master 


Issue is still persist.    (examples/get-started/hello-world/main/hello_world_main.c):


image


image

**Comment by kolipakakondal** [comment]
> Hi @kolipakakondal
> 
> Tested under: OS - Windows 10 ESP - IDF: master
> 
> Issue is still persist. (examples/get-started/hello-world/main/hello_world_main.c): BUT compare to previous test - this time I can see less warnings :)
> 
Ok, thanks for verifying @AndriiFilippov. How did you verify - is it through the PR update site or Espressif-IDE? Probably that that will help me to narrow down the problem

**Comment by AndriiFilippov** [comment]
@kolipakakondal  always through the Espressif-IDE

**Comment by kolipakakondal** [comment]
Hi @AndriiFilippov Could you confirm the espressif-ide build number you've used. I have verified on windows machine and it seems to be working fine.

Could you also share the parser log and error log
https://github.com/espressif/idf-eclipse-plugin/blob/master/FAQ.md#how-do-i-access-cdt-parser-error-log
https://github.com/espressif/idf-eclipse-plugin/blob/master/FAQ.md#how-do-i-access-the-error-log


**My testing environment:**
Windows 10 Pro
espressif-ide: Version: 2.6.0 and Build id: 20220811-1438
PR download link:https://github.com/espressif/idf-eclipse-plugin/suites/7772406231/artifacts/326977009


ide_1

**Comment by kolipakakondal** [comment]
Ok, I am able to reprodce this issue with esp-idf master branch(earlier I was trying with some old esp-idf master). Looks like we have this issue on our released verson of espressif-ide v2.6.0 as well if we build with esp-idf master branch.  This issue is not specific to PR

I will check further on this.

**Comment by kolipakakondal** [comment]
I'm closing this PR as the issue mentioned is not specific to this PR. Will create a new Jira ticket and track it.

**Comment by kolipakakondal** [comment]
> 

Yes, you're right, you should be able to achieve the same using the approach you've mentioned also. But the problem would be - it would add ALL the components from esp-idf directly which is not correct and causing indexer problems due to a conflict of source files and headers. To avoid this, esp_idf_components were added only with the components(virtual links only) which were used in the project that is based on the `compile_commands.json` file generated by CMake during the build

**Pull request merged**
