### PR TITLE
IEP-888: Fixing the installation for only selected tools

### PR DESCRIPTION
**Pull request by alirana01**
## Description

Removed path dependency on export script in python for system path

Fixes # ([IEP-888](https://jira.espressif.com:8443/browse/IEP-888))

## Type of change

Please delete options that are not relevant.
- Bug fix (_**can be a breaking change around tools installation wizard proper testing required**_)

## How has this been tested?

In Install Tools Wizard, select only one tool install it. Close the wizard, relaunch and install one more tool other than the one selected it should work fine. Also install all the tools after this.
Build project and see should be working fine.
Now switch to a different idf version and install tools via the wizard create a new project and build it. The build should work fine

**Test Configuration**:
* ESP-IDF Version: All
* OS (Windows,Linux and macOS): All

## Checklist
- [x] PR Self Reviewed
- [x] Applied Code formatting
- [ ] Verified on all platforms - Windows,Linux and macOS

### CODE REVIEW

**Review by alirana01 — COMMENTED** [review]
Removing dependency around the python export script.

**Comment by AndriiFilippov** [comment]
@alirana01 
Windows - LGTM. 
Linux - still same error.

**Comment by AndriiFilippov** [comment]
@alirana01 hi !
Linux - same issue still exist.

**Comment by AndriiFilippov** [comment]
@alirana01 issue still persist.

**Comment by AndriiFilippov** [comment]
Building in: /Applications/Espressif-IDE.app/Contents/MacOS/workspace12312/hello_world/build
Configuring in: /Applications/Espressif-IDE.app/Contents/MacOS/workspace12312/hello_world/build
cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE=/Users/andrii/esp/esp-idf-v5.0.1/tools/cmake/toolchain-esp32s2.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCCACHE_ENABLE=1 -DIDF_TARGET=esp32 /Applications/Espressif-IDE.app/Contents/MacOS/workspace12312/hello_world
-- Found Git: /usr/bin/git (found version "2.30.1 (Apple Git-130)") 
CMake Warning at /Users/andrii/esp/esp-idf-v5.0.1/tools/cmake/project.cmake:337 (message):
  enabled ccache in build but ccache program not found
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)


-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- The ASM compiler identification is GNU
-- Found assembler: /Users/andrii/.espressif/tools/xtensa-clang/14.0.0-38679f0333/xtensa-esp32-elf-clang/bin/xtensa-esp32-elf-gcc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /Users/andrii/.espressif/tools/xtensa-clang/14.0.0-38679f0333/xtensa-esp32-elf-clang/bin/xtensa-esp32-elf-gcc
-- Check for working C compiler: /Users/andrii/.espressif/tools/xtensa-clang/14.0.0-38679f0333/xtensa-esp32-elf-clang/bin/xtensa-esp32-elf-gcc - broken
CMake Error at /Users/andrii/.espressif/tools/cmake/3.24.0/cmake-3.24.0-macos-universal/CMake.app/Contents/share/cmake-3.24/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

-- Configuring incomplete, errors occurred!
See also "/Applications/Espressif-IDE.app/Contents/MacOS/workspace12312/hello_world/build/CMakeFiles/CMakeOutput.log".
See also "/Applications/Espressif-IDE.app/Contents/MacOS/workspace12312/hello_world/build/CMakeFiles/CMakeError.log".
    "/Users/andrii/.espressif/tools/xtensa-clang/14.0.0-38679f0333/xtensa-esp32-elf-clang/bin/xtensa-esp32-elf-gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Applications/Espressif-IDE.app/Contents/MacOS/workspace12312/hello_world/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/Users/andrii/.espressif/tools/ninja/1.10.2/ninja cmTC_76a47 && [1/2] Building C object CMakeFiles/cmTC_76a47.dir/testCCompiler.c.obj
    [2/2] Linking C executable cmTC_76a47
    FAILED: cmTC_76a47 
    : && /Users/andrii/.espressif/tools/xtensa-clang/14.0.0-38679f0333/xtensa-esp32-elf-clang/bin/xtensa-esp32-elf-gcc -mlongcalls -Wno-frame-address  CMakeFiles/cmTC_76a47.dir/testCCompiler.c.obj -o cmTC_76a47   && :
    /Users/andrii/.espressif/tools/xtensa-clang/14.0.0-38679f0333/xtensa-esp32-elf-clang/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /Users/andrii/.espressif/tools/xtensa-clang/14.0.0-38679f0333/xtensa-esp32-elf-clang/bin/../libexec/gcc/xtensa-esp32-elf/8.4.0/liblto_plugin.so: error loading plugin: dlopen(/Users/andrii/.espressif/tools/xtensa-clang/14.0.0-38679f0333/xtensa-esp32-elf-clang/bin/../libexec/gcc/xtensa-esp32-elf/8.4.0/liblto_plugin.so, 0x0002): tried: '/Users/andrii/.espressif/tools/xtensa-clang/14.0.0-38679f0333/xtensa-esp32-elf-clang/bin/../libexec/gcc/xtensa-esp32-elf/8.4.0/liblto_plugin.so' (), '/Users/andrii/.espressif/tools/xtensa-clang/14.0.0-38679f0333/xtensa-esp32-elf-clang/libexec/gcc/xtensa-esp32-elf/8.4.0/liblto_plugin.so' ()
    collect2: error: ld returned 1 exit status
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  /Users/andrii/esp/esp-idf-v5.0.1/tools/cmake/project.cmake:342 (__project)
  CMakeLists.txt:6 (project)


cmake --build . -- -v
ninja: error: loading 'build.ninja': No such file or directory
Build complete (0 errors, 0 warnings): /Applications/Espressif-IDE.app/Contents/MacOS/workspace12312/hello_world/build
Total time taken to build the project: 6,239 ms

**Comment by AndriiFilippov** [comment]
@alirana01 hi !
On Linux issue is still persist. 


```
Building in: /home/osboxes/Desktop/Espressif-IDE/workspacebhbhb/njnjnn/build
Configuring in: /home/osboxes/Desktop/Espressif-IDE/workspacebhbhb/njnjnn/build
cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE=/home/osboxes/e/esp-idf-v5.0.1/tools/cmake/toolchain-esp32.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCCACHE_ENABLE=1 -DIDF_TARGET=esp32 /home/osboxes/Desktop/Espressif-IDE/workspacebhbhb/njnjnn
/home/osboxes/.espressif/tools/cmake/3.24.0/cmake-3.24.0-linux-aarch64/bin/cmake: 1: ELF�ВC@Xy�@8: not found
/home/osboxes/.espressif/tools/cmake/3.24.0/cmake-3.24.0-linux-aarch64/bin/cmake: 1: Syntax error: word unexpected (expecting ")")
cmake --build . -- -v
/home/osboxes/.espressif/tools/cmake/3.24.0/cmake-3.24.0-linux-aarch64/bin/cmake: 1: ELF�ВC@Xy�@8: not found
/home/osboxes/.espressif/tools/cmake/3.24.0/cmake-3.24.0-linux-aarch64/bin/cmake: 1: Syntax error: word unexpected (expecting ")")
Build complete (0 errors, 0 warnings): /home/osboxes/Desktop/Espressif-IDE/workspacebhbhb/njnjnn/build
Total time taken to build the project: 311 ms
```

**Comment by AndriiFilippov** [comment]
@alirana01 hi ! 

Linux fixed 👍 
LGTM

**Review by AndriiFilippov — APPROVED** [review]

**Pull request merged**
