### PR TITLE
IEP-296: Show total time took for compilation / build (IEP-297)

### PR DESCRIPTION
**Pull request by kolipakakondal**
Screenshot 2020-12-07 at 12 55 58 PM

### CODE REVIEW

**Comment by kolipakakondal** [comment]
Sorry for the inconvenience, we have fixed this with https://github.com/espressif/idf-eclipse-plugin/pull/155

We will update here once it's released

**Comment by kifantidis** [comment]
Hey @kolipakakondal .

May I ask where is this IDFBuildConfigurations file located ? Is it inside .eclipse file ? or .esspressif maybe ? Or it is not possible for me to change and have access to this feature ?

**Comment by kolipakakondal** [comment]
Here is the local build https://github.com/espressif/idf-eclipse-plugin/suites/1619872529/artifacts/29752430

**Comment by kifantidis** [comment]
> 
> 
> Here is the local build https://github.com/espressif/idf-eclipse-plugin/suites/1619872529/artifacts/29752430

Thank you very much !

**Review by projectgus — APPROVED** [review]

**Pull request merged**
