### PR TITLE
IEP-417: Eclipse 4.20 support and fix installation issues

### PR DESCRIPTION
**Pull request by kolipakakondal**
Fix for the below issues reported
https://github.com/espressif/idf-eclipse-plugin/issues/299
https://github.com/espressif/idf-eclipse-plugin/issues/260

### CODE REVIEW

**Comment by kolipakakondal** [comment]
Hi @sigmaaa @alirana01 Could you help to validate this by installing these artifacts on Eclipse 4.20, 4.19 and 4.18 CPP versions

**Comment by kolipakakondal** [comment]
I was checking on macOS with Eclipse 2021-03 and Eclipse 2021-06, it seems to be working fine.

**Review by alirana01 — APPROVED** [review]
The plugin works on windows and Linux only small thing that I noticed on windows was that the errors were not resolved in the editor UI for the c file even after the build this can be something related to my environment although this was not found on Linux.

**Comment by kolipakakondal** [comment]
Thank @alirana01 for verifying this, will release 2.1.2 with this fix and plan 2.2.0 later as lot of users started using Eclipse 4.20

**Pull request merged**
