### PR TITLE
IEP-351: Automatic loading of svd for Peripherals view

### PR DESCRIPTION
**Pull request by alirana01**
Eclipse's build in peripherals view for openOCD debugging allows us to supply the svd files for the memory browser. We have automated that process by keeping the svd files in the plugin directory.

Fixes # ([IEP-351](https://jira.espressif.com:8443/browse/IEP-351))

## Type of change

- New feature (non-breaking change which adds functionality)

## How has this been tested?

Create a project and then create and Espressif based open ocd debug configuration. See that svd tab has the path for the selected target. Try to change the target from the launch bar and then also in openocd debugger tab and see that the changes are reflected in the svd tab. Also tried testing without going into the svd tab to see if the peripherals view loads the peripherals from the svd file and it does.
* OS (Windows,Linux and macOS):

## Checklist
- [x] PR Self Reviewed
- [x] Applied Code formatting
- [x] Verified on all platforms - Windows,Linux and macOS

### CODE REVIEW

**Review by alirana01 — COMMENTED** [review]
PR self reviewd

**Review by kolipakakondal — APPROVED** [review]
Thanks @alirana01 for the PR. LGTM

**Comment by kolipakakondal** [comment]
One thing - Looks like svd path is not dynamically getting updated after the launch target changes. I have changed the launch target from esp32 to esp32s2 in the eclipse toolbar drop-down also in the debugger tab and then when I moved to the svd tab still shows the esp32 which was my previous target selection

it would be great if we could update this dynamically

**Comment by alirana01** [comment]
> One thing which I noticed - Looks like svd path is not dynamically getting updated after the launch target changes. I have changed the launch target from esp32 to esp32s2 in the eclipse toolbar drop-down also in the debugger tab and then when I moved to the svd tab still shows the esp32 which was my previous target selection
> 
> it would be great if we could update this dynamically

I have updated and fixed this in latest commit @AndriiFilippov can you please test and verify the flows mentioned by @kolipakakondal  as well

**Comment by alirana01** [comment]
> Hi @alirana01 !
> 
> Tested under: OS - Windows 10 ESP-IDF: 5.1
> 
> I have created new configuration file and could not see any path:
> 
> image I do see this file in workspace folder and here is my logs.
> 
> [log1.txt](https://github.com/espressif/idf-eclipse-plugin/files/9722537/log1.txt)

@AndriiFilippov can you please verify this again on all platforms

**Comment by AndriiFilippov** [comment]
@alirana01 

Tested under: 
OS - Windows 10 / Linux 
ESP-IDF: master

LGTM, only targets (esp32c2) not getting updated based on supported targets in OpenOcd or EspIDF. Create Jira ticket https://jira.espressif.com:8443/browse/IEP-774

image
image

**Pull request merged**
