### PR TITLE
fix: Keep all the menu items under ESP-IDF main menu

### PR DESCRIPTION
**Pull request by kolipakakondal**
## Description

Reorganizing ESP-IDF menu items
Screenshot 2024-05-28 at 12 41 12 AM

## Type of change
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How has this been tested?

Verify whether all the menu options available and functional

**Test Configuration**:
* ESP-IDF Version: NA
* OS (Windows,Linux and macOS): macOS

## Dependent components impacted by this PR:

- ESP-IDF Menu actions

## Checklist
- [x] PR Self Reviewed
- [x] Applied Code formatting
- [ ] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

## Summary by CodeRabbit

- **New Features**
  - Simplified command labels and names for various ESP-IDF functionalities for better clarity and user experience.
  
- **Bug Fixes**
  - Updated context menu operations in the project test suite to match the simplified command names.

- **Documentation**
  - Improved descriptions for command labels and names related to ESP-IDF functionalities.

- **Refactor**
  - Removed "ESP-IDF:" prefix from command labels and names to streamline user interface elements.

### CODE REVIEW

**Review by sigmaaa — APPROVED** [review]
LGTM!

**Comment by kolipakakondal** [comment]
@AndriiFilippov Can you verify this?

**Comment by AndriiFilippov** [comment]
@kolipakakondal hi ! 

Tested under: 
OS - Windows 10 
ESP-IDF: v5.2.1


Able to access and run all features under "ESP-IDF" menu. 
LGTM 👍

**Review by AndriiFilippov — APPROVED** [review]

**Review by alirana01 — COMMENTED** [review]
LGTM, surprisingly SWTBot is figuring out the submenu without any further required changes

**Pull request merged**
