### PR TITLE
IEP-1265: Debug Process Hangs

### PR DESCRIPTION
**Pull request by alirana01**
## Description

The port handling logic was flawed added proper code to verify and assign ports with a logic for retries as well. 
Also changed the debugger tab so that the gdb client controls are only enabled when the openOCD server is not started from the IDE.

Fixes # ([IEP-1265](https://jira.espressif.com:8443/browse/IEP-1265))

## Type of change

Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)

## How has this been tested?

Try debugging on mac os and verify that openocd is able to connect. Also start openocd only from cli and try to connect debugger

**Test Configuration**:
* ESP-IDF Version: all
* OS (Windows,Linux and macOS): any

## Checklist
- [x] PR Self Reviewed
- [x] Applied Code formatting
- [ ] Verified on all platforms - Windows,Linux and macOS

## Summary by CodeRabbit

- **Bug Fixes**
	- Enhanced port availability checking for improved reliability and logging.
	- Adjusted how the launch configuration handles port assignments, ensuring ports are only set when necessary.
	- Improved resource cleanup during launch cancellation or failure.

- **New Features**
	- Introduced a new user interface component for GDB client controls, improving organization and user experience.
	- Updated logic for GDB server configuration to simplify port retrieval, enhancing usability.
	- Improved interaction logic between the GDB server and client configurations for better user experience.
	- Added functionality to disable GDB client controls when the server is running, preventing user errors.
	- Enhanced GDB backend functionality with improved error handling and process management.
	- Introduced a singleton class for managing processes associated with different launch names, streamlining process management.
	- Enhanced process management capabilities in the launch process, including initialization and termination of processes.

### CODE REVIEW

**Comment by kolipakakondal** [comment]
@alirana01 Having the same issue with the PR as well.
Screenshot 2024-07-26 at 5 03 20 PM

[stack.log](https://github.com/user-attachments/files/16390987/stack.log)

**Review by alirana01 — COMMENTED** [review]
Self Review

**Review by sigmaaa — COMMENTED** [review]
LGTM

**Comment by kolipakakondal** [comment]
This didn't work for me. Need to check further.

Please find the attached IDE error log.
[ide.log](https://github.com/user-attachments/files/17093533/ide.log)

**Comment by kolipakakondal** [comment]
Hi @alirana01 , thanks for the PR. I verified the debugging with the ESP32-Wrover-Kit, and it seems to be working fine. I no longer see the issue I reported earlier. However, I previously tested with the ESP32-C6, but my cable is currently missing, so I cannot verify it at this moment wit the c6.

**Comment by kolipakakondal** [comment]
Hi @AndriiFilippov Please test further

**Review by kolipakakondal — APPROVED** [review]
LGTM

**Comment by AndriiFilippov** [comment]
@alirana01 hi ! 

Tested under: 
OS: Mac arm64
ESP-IDF: v5.3.1 

1) I have occupide `3333 port` :
```
andriifilippov@Andriis-MacBook-Pro ~ % sudo lsof -i :3333
Password:
COMMAND   PID           USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
openocd 11100 andriifilippov    5u  IPv4 0x4a2957386a35d1ed      0t0  TCP localhost:dec-notes (LISTEN)
Python  65956 andriifilippov    4u  IPv6 0x4a29572a062c2c1d      0t0  TCP *:dec-notes (LISTEN)
```
and start debug with GDB
 Screenshot 2024-10-10 at 13 42 13
 and I just see endless amount of retries without switching to 3334 port. 
 I am not able to stop the process. 
Screenshot 2024-10-10 at 13 48 49


2) I thought this logic is applicable to all ports, such as tcl and Telnet 
Screenshot 2024-10-10 at 13 45 00
but it doesn't. 
If those ports are occupied:
```
andriifilippov@Andriis-MacBook-Pro ~ % sudo lsof -i :6666
Password:
COMMAND   PID           USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
openocd 11100 andriifilippov    6u  IPv4 0x4a2957386a35af6d      0t0  TCP localhost:6666 (LISTEN)
```
then it just throws error message, not looking for available port: 


```
** Verify OK **
** Flashing done for partition_table/partition-table.bin in 460 ms **
** Total programming time 4491 ms **
** Resetting Target **
Info : JTAG tap: esp32.cpu0 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : JTAG tap: esp32.cpu1 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : [esp32.cpu0] requesting target halt and executing a soft reset
Info : [esp32.cpu0] Debug controller was reset.
Info : [esp32.cpu0] Core was reset.
Info : [esp32.cpu0] Target halted, PC=0x500000CF, debug_reason=00000000
Info : [esp32.cpu0] Reset cause (3) - (Software core reset)
Info : [esp32.cpu1] requesting target halt and executing a soft reset
Info : [esp32.cpu0] Core was reset.
Info : [esp32.cpu1] Debug controller was reset.
Info : [esp32.cpu1] Core was reset.
0
Started by GNU MCU Eclipse
Error: couldn't bind tcl to socket on port 6666: Address already in use
Please refer to the troubleshooting guide below to identify the problem.
```

**Comment by AndriiFilippov** [comment]
@alirana01 hi !

Issue still persist

**Comment by alirana01** [comment]
@AndriiFilippov please use these guidelines there must be another way to occupy the ports to verify this anyway at times the serial id for the connected boards is similar we need to specify it different for each board I have attached a conversation on the original jira ticket for you to track and verify.

**Comment by AndriiFilippov** [comment]
@alirana01 hi!

Tested, but it seems the issue is still persist.

Reproduce: 
I have occupied port 3333 using python script from cli -> open IDE and run Debug -> it does not switch to 3334 and the process just stack. 

image

**Comment by kolipakakondal** [comment]
Hi @alirana01 

**Tested environment:**
esp32c6
macos arm64
esp-idf v5.3

**Test Procedure:**
When I clicked on Debug, the IDE entered debug mode and successfully started the debug session. However, It was unable to point to the exact breakpoint in the file. This is a known issue when there’s a flash mapping problem.

Screenshot 2024-11-18 at 4 59 13 PM


I then clicked on the Terminate button, but it failed to terminate the debug session, causing the IDE to hang. I was unable to perform any actions, so I had to restart it.


After restarting, I clicked on Debug again. This time, it didn’t initiate debug mode and got stuck at the "Configuring GDB" state, as shown below. Nothing is happening even when I click on terminate button

Screenshot 2024-11-18 at 4 58 51 PM

When I verify in terminal, I see that port 3333 occupied 

```
 % lsof -i tcp:3333
COMMAND   PID           USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
openocd 26656 kondalkolipaka    5u  IPv4 0xa0702c3054b6db85      0t0  TCP localhost:dec-notes (LISTEN)
```

I restarted Eclipse, increased the flash size, rebuilt the project, and flashed it again.

When I clicked on Debug this time, no flash mapping issues were reported. However, it didn’t stop at the breakpoint. I decided to kill and restart the debug session, but then I encountered the same old issue, as shown below.

Screenshot 2024-11-18 at 5 16 35 PM


```
% lsof -i tcp:3333
COMMAND     PID           USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
openocd   43769 kondalkolipaka    7u  IPv4 0xa0702c3054b6d00d      0t0  TCP localhost:dec-notes (LISTEN)
openocd   43769 kondalkolipaka    8u  IPv4 0xa0702c3054b6a22d      0t0  TCP localhost:dec-notes->localhost:65256 (ESTABLISHED)
riscv32-e 43770 kondalkolipaka   11u  IPv4 0xa0702c3054b6e6fd      0t0  TCP localhost:65256->localhost:dec-notes (ESTABLISHED
```

**Comment by kolipakakondal** [comment]
After further troubleshooting, I was able to debug it properly with esp32c6. However, when issues such as connecting to the board, timeout errors, or flash mapping problems occur, the IDE does not handle them gracefully and encounters the previously reported issues, such as the IDE getting stuck.

image

**Comment by kolipakakondal** [comment]
The same problem occurs if the 3333 port is occupied (e.g., when I start OpenOCD from the terminal to block the port) and then try to start the debug session from Eclipse (both server and client).

image

**Comment by alirana01** [comment]
@kolipakakondal  I have updated the code. I had to use some internal classes from eclipse as seemingly they seem to be fine but required a lot of changes and for some reason they didn't bother making the internal implementation's constructor extendable so reused their code and did the required modifications so killing a process would not bounce back errors. This should resolve some of the issues you mentioned I couldn't get to reproduce the issue for debugger not opening up the files except once. Please try to test if this resolves it better

@AndriiFilippov also take a look and try with new builds

**Comment by alirana01** [comment]
@AndriiFilippov @kolipakakondal I have updated with recent changes please take a look again

**Comment by AndriiFilippov** [comment]
@alirana01  
Now there is only this errors on Debug start. 
[logsDebugStart.log](https://github.com/user-attachments/files/17816884/logsDebugStart.log)

I am able to Debug but when I stop process sometime (random) it is throws this error 

```
org.xml.sax.SAXParseException; lineNumber: 65; columnNumber: 1; Content is not allowed in trailing section. occurred while reading launch configuration file: /Users/andriifilippov/workspaceTestthisfancypropernocdgdb1111/.metadata/.plugins/org.eclipse.debug.core/.launches/we21er Debug.launch.
org.xml.sax.SAXParseException; lineNumber: 65; columnNumber: 1; Content is not allowed in trailing section.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
```

and delete Debug config 
Screenshot 2024-11-19 at 15 48 41


OR sometime it stops process successfully (Activity Monitor shows no openOCD or GDB process) but it gets stuck on the next execution.  without any error or warning.

**Comment by alirana01** [comment]
> @alirana01 Now there is only this errors on Debug start. [logsDebugStart.log](https://github.com/user-attachments/files/17816884/logsDebugStart.log)
> 
> I am able to Debug but when I stop process sometime (random) it is throws this error
> 
@kolipakakondal  @sigmaaa can you guys please verify this on your macs please I cannot find a consistent way to reproduce  this

**Comment by AndriiFilippov** [comment]
@alirana01 hi !

Tested: 
OS - Mac arm64
ESP-IDF: v5.3.1 

I am still encountering issues with starting and stopping the debugging process:
I start the debugger and then stop the process, ensuring I wait for the process to fully terminate. 
I monitor the **Activity Monitor** to confirm that both the O**penOCD** and **GDB** processes have completely stopped. Once both processes are terminated, I attempt to start debugging again, but it works inconsistently. The debugger sometimes freezes, and I cannot stop it by clicking the Stop button.
During this test, I did not add breakpoints or close any files or debugging windows. The sequence was simply: start debugging, stop debugging.

**Comment by AndriiFilippov** [comment]
2. A similar situation occurs when port 3333 is occupied by another process. The debugger starts on port 3334, but with inconsistent results. It generally works, but it is not stable.


3. I cannot see the Variables.
Screenshot 2024-11-22 at 11 23 29

4. I wanted to ask if the information about the port change is important for the user. If so, I would make the line about the port change more prominent. Now there is only brief note above: 
Screenshot 2024-11-22 at 11 51 15

**Comment by AndriiFilippov** [comment]
@alirana01 
apart from that, everything else works.
LGTM 👍

**Comment by AndriiFilippov** [comment]
@sigmaaa @kolipakakondal please, review.

**Review by sigmaaa — APPROVED** [review]
LGTM

**Pull request merged**
