### PR TITLE
Added Microsoft C++ Build tools to the dependency list. (IEP-365)

### PR DESCRIPTION
**Pull request by Bjohnson131**
Simple change to the readme which adds  Microsoft's c++ build tools, required by IDF to install dependencies.

### CODE REVIEW

**Comment by kolipakakondal** [comment]
Hi @Bjohnson131 - I believe this is required only when you're working with python 3.8?

**Comment by Bjohnson131** [comment]
> Hi @Bjohnson131 - I believe this is required only when you're working with python 3.8?

It's a requirement for ESP-IDF, so I put it in with the hope it'll help others.

**Comment by kolipakakondal** [comment]
Hi @Bjohnson131 Thanks, If this a requirement for esp-idf, we would like to mention it as part of the esp-idf documentation well. @projectgus Could you clarify this.

**Comment by projectgus** [comment]
Hi @Bjohnson131 @kolipakakondal,

We do our best not to require a native C/C++ compiler for ESP-IDF.

I may be wrong, but I am guessing the situation was that a Python package is being installed that has no "binary wheel" for Windows, so "pip" tries to compile it - and this does need a native Windows C/C++ compiler.

Recently on ESP-IDF master branch we've had a few cases where this was the case (for [example this issue](https://github.com/espressif/esp-idf/issues/6111)) but we try to fix them before any ESP-IDF releases (see @georgik's comment in the linked issue about an updated Windows installer that uses the espressif pip mirror).

If you have some details about which ESP-IDF version(s) required native build tools, the Python version, and/or the log output when this happened, then we can chase it up further.

**Comment by georgik** [comment]
@Bjohnson131 There is no need for Visual C++.

We already build all missing Python Wheels for Python 3.8, 3.9 for Windows and they're available at: https://dl.espressif.com/pypi/
The build of Wheels and final artefacts are here: https://github.com/espressif/idf-python-wheels

It's sufficient to run the installation using ESP-IDF installer 2.5 https://dl.espressif.com/dl/esp-idf-tools-setup-online-2.5.exe or set environment variable to PIP_EXTRA_INDEX_URL https://dl.espressif.com/pypi/ and run install.bat. 

Visual C++ is not even required for new 2.6 Beta Installer which contains also Eclipse: https://github.com/espressif/idf-installer/releases/tag/online-2.6-beta-11

**Comment by Bjohnson131** [comment]
> @Bjohnson131 There is no need for Visual C++.
> 
> We already build all missing Python Wheels for Python 3.8, 3.9 for Windows and they're available at: https://dl.espressif.com/pypi/
> The build of Wheels and final artefacts are here: https://github.com/espressif/idf-python-wheels
> 
> It's sufficient to run the installation using ESP-IDF installer 2.5 https://dl.espressif.com/dl/esp-idf-tools-setup-online-2.5.exe or set environment variable to PIP_EXTRA_INDEX_URL https://dl.espressif.com/pypi/ and run install.bat.
> 
> Visual C++ is not even required for new 2.6 Beta Installer which contains also Eclipse: https://github.com/espressif/idf-installer/releases/tag/online-2.6-beta-11

Hmm, this info should probably be in the installation guide then..?

**Comment by georgik** [comment]
@Bjohnson131 Thank you for pointing out that problem. It should be part of installation guide. We will update it with Windows Installer update.

**Comment by georgik** [comment]
@Bjohnson131 MR is waiting for review. Documentation updated. The link points to new landing page for downloading Windows Installer https://dl.espressif.com/dl/esp-idf/

**Comment by kolipakakondal** [comment]
Closing this issue as this was already addressed in esp-idf doc

**Pull request closed without merging**
