### PR TITLE
IEP-1064 Improvements around debugging Documentation

### PR DESCRIPTION
**Pull request by sigmaaa**
## Description

the main details about debugging separated from the debug documentation to the main readme

Fixes # ([IEP-1064](https://jira.espressif.com:8443/browse/IEP-1064))

## Type of change

Please delete options that are not relevant.
- New feature (non-breaking change which adds functionality)

## How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- Test A
- Test B

**Test Configuration**:
* ESP-IDF Version:
* OS (Windows,Linux and macOS):

## Dependent components impacted by this PR:

- Component 1
- Component 2

## Checklist
- [ ] PR Self Reviewed
- [ ] Applied Code formatting
- [ ] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

## Summary by CodeRabbit

- **Documentation**
	- Updated the "Debugging the Project" section with additional information on installing drivers for Windows users, including a note and a reference link for detailed instructions.

### CODE REVIEW

**Comment by AndriiFilippov** [comment]
@sigmaaa hi !

In my opinion, since 90% of our users are using Windows, I would duplicate the information about Zadig in the Debug section. Currently, this information about Zadig is in the DFU section, but few people use it, so there is a high probability that the user is unlikely to see it. Debugging on Windows is impossible without it.

image

**Comment by sigmaaa** [comment]
Hi @AndriiFilippov,
thank you for review. I added a new note which mentions driver installation via a link in the last commit

**Comment by sigmaaa** [comment]
> Hi @sigmaaa Can you also use the icons from [here](https://github.com/espressif/idf-eclipse-plugin/tree/master/docs/images/icons) for referrring debug icons and others.
> 
> For example, I have used launch icon [here](https://github.com/espressif/idf-eclipse-plugin?tab=readme-ov-file#flashing-the-project)

Hi @kolipakakondal, thank you for review. I added an icon in the latest commit

**Review by sigmaaa — COMMENTED** [review]
Self reviewed. I think the Drivers installation part can be improved

**Comment by sigmaaa** [comment]
updated guide URL to the espressif zadig doc

**Review by kolipakakondal — APPROVED** [review]
LGTM

**Pull request merged**
